import type { Metadata } from "next";
import SideBar from "@/components/dashboard/side-bar/side-bar";
import Navbar from "@/components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <div className="flex flex-1">
        <SideBar />
        <div className="flex-1 p-4 bg-gray-100">
          {children}
        </div>
      </div>
    </div>
  );
}
