import type { Metadata } from "next";
import SideBar from "@/components/dashboard/side-bar/side-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen flex">
      <SideBar />
      <div className="flex-1 p-4">{children}</div>
    </main>
  );
}
